version: 2.0.0.{build}
skip_tags: true
image: Visual Studio 2022
build_script:
- ps: ./.ci/build.ps1
test_script:
- ps: ./.ci/test.ps1
artifacts:
- path: artifacts/*.nupkg
- path: artifacts/*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: WvkGggPwnMYbDvVC3e2tfWJOCsKG3PsfUtN+l9VsqlvyT0vQrKlrIzaonctNRdWE
  on:
    branch: /^master|release\/.+$/